version: '3.8'

services:
  # Backend Service
  api:
    build: ./backend
    container_name: idp-backend
    ports:
      - "7860:7860" 
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app 

    command: uvicorn app.main:app --host 0.0.0.0 --port 7860 --reload

  # Frontend Service
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: idp-frontend
    ports:
      - "5173:80" 
    depends_on:
      - api